// Auto-generated by zitejs generate from zite.config.json. Do not edit manually.
// zitejs/integrations — an integration's credentials by its zite.config.json entry name.
//
// Usage in endpoints (src/api/*.ts) and automations (src/index.ts):
//   import { integrations } from 'zitejs/integrations';
//
//   const { accessToken } = await integrations.get('<entry name>');
//
// A workspace connection that isn't connected throws a ZiteError. A per-user
// entry answers `missing`/`expired` with a connectUrl for the signed-in user.
//
// Call get where the value is used, not once at module scope: a token refreshed
// mid-run is what the next call returns.

import { createIntegrationsClient } from 'zitejs/runtime';
import type { Connected, NeedsConnect } from 'zitejs/runtime';

export type { Connected, NeedsConnect };

export type IntegrationName = 'github';

export type IntegrationByName = {
  'github': Connected;
};

export const integrations = createIntegrationsClient<IntegrationByName>();
