// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AdminListEp } from '../src/api/adminList';
import type { default as _AdminListCoachesEp } from '../src/api/adminListCoaches';
import type { default as _AdminLoginEp } from '../src/api/adminLogin';
import type { default as _AdminReviewCoachEp } from '../src/api/adminReviewCoach';
import type { default as _AdminSaveEp } from '../src/api/adminSave';
import type { default as _AdminStatsEp } from '../src/api/adminStats';
import type { default as _ApplyCoachEp } from '../src/api/applyCoach';
import type { default as _BodyyarChatEp } from '../src/api/bodyyarChat';
import type { default as _CancelCoachingRequestEp } from '../src/api/cancelCoachingRequest';
import type { default as _ChallengeProgressEp } from '../src/api/challengeProgress';
import type { default as _CreateCoachingRequestEp } from '../src/api/createCoachingRequest';
import type { default as _GenerateWorkoutPlanEp } from '../src/api/generateWorkoutPlan';
import type { default as _GetCatalogEp } from '../src/api/getCatalog';
import type { default as _GetCoachPanelEp } from '../src/api/getCoachPanel';
import type { default as _GetMeEp } from '../src/api/getMe';
import type { default as _GetMessagesEp } from '../src/api/getMessages';
import type { default as _JamendoTracksEp } from '../src/api/jamendoTracks';
import type { default as _KapooshProductsEp } from '../src/api/kapooshProducts';
import type { default as _ListConversationsEp } from '../src/api/listConversations';
import type { default as _LogActivityEp } from '../src/api/logActivity';
import type { default as _RedeemRewardEp } from '../src/api/redeemReward';
import type { default as _SaveAvailabilityEp } from '../src/api/saveAvailability';
import type { default as _SaveCoachPlanEp } from '../src/api/saveCoachPlan';
import type { default as _SaveListeningEp } from '../src/api/saveListening';
import type { default as _SaveProfileEp } from '../src/api/saveProfile';
import type { default as _SendMessageEp } from '../src/api/sendMessage';
import type { default as _StartConversationEp } from '../src/api/startConversation';
import type { default as _TrackCampaignViewEp } from '../src/api/trackCampaignView';
import type { default as _UpdateCoachProfileEp } from '../src/api/updateCoachProfile';
import type { default as _UpdateRequestStatusEp } from '../src/api/updateRequestStatus';

type _AdminListCfg = typeof _AdminListEp;
export type AdminListInputType = NonNullable<_AdminListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminListCfg['execute']>[0]['input'];
export type AdminListOutputType = Awaited<ReturnType<_AdminListCfg['execute']>>;
export const adminList = createCaller<AdminListInputType, AdminListOutputType>('adminList');

type _AdminListCoachesCfg = typeof _AdminListCoachesEp;
export type AdminListCoachesInputType = NonNullable<_AdminListCoachesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminListCoachesCfg['execute']>[0]['input'];
export type AdminListCoachesOutputType = Awaited<ReturnType<_AdminListCoachesCfg['execute']>>;
export const adminListCoaches = createCaller<AdminListCoachesInputType, AdminListCoachesOutputType>('adminListCoaches');

type _AdminLoginCfg = typeof _AdminLoginEp;
export type AdminLoginInputType = NonNullable<_AdminLoginCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminLoginCfg['execute']>[0]['input'];
export type AdminLoginOutputType = Awaited<ReturnType<_AdminLoginCfg['execute']>>;
export const adminLogin = createCaller<AdminLoginInputType, AdminLoginOutputType>('adminLogin');

type _AdminReviewCoachCfg = typeof _AdminReviewCoachEp;
export type AdminReviewCoachInputType = NonNullable<_AdminReviewCoachCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminReviewCoachCfg['execute']>[0]['input'];
export type AdminReviewCoachOutputType = Awaited<ReturnType<_AdminReviewCoachCfg['execute']>>;
export const adminReviewCoach = createCaller<AdminReviewCoachInputType, AdminReviewCoachOutputType>('adminReviewCoach');

type _AdminSaveCfg = typeof _AdminSaveEp;
export type AdminSaveInputType = NonNullable<_AdminSaveCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveCfg['execute']>[0]['input'];
export type AdminSaveOutputType = Awaited<ReturnType<_AdminSaveCfg['execute']>>;
export const adminSave = createCaller<AdminSaveInputType, AdminSaveOutputType>('adminSave');

type _AdminStatsCfg = typeof _AdminStatsEp;
export type AdminStatsInputType = NonNullable<_AdminStatsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminStatsCfg['execute']>[0]['input'];
export type AdminStatsOutputType = Awaited<ReturnType<_AdminStatsCfg['execute']>>;
export const adminStats = createCaller<AdminStatsInputType, AdminStatsOutputType>('adminStats');

type _ApplyCoachCfg = typeof _ApplyCoachEp;
export type ApplyCoachInputType = NonNullable<_ApplyCoachCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ApplyCoachCfg['execute']>[0]['input'];
export type ApplyCoachOutputType = Awaited<ReturnType<_ApplyCoachCfg['execute']>>;
export const applyCoach = createCaller<ApplyCoachInputType, ApplyCoachOutputType>('applyCoach');

type _BodyyarChatCfg = typeof _BodyyarChatEp;
export type BodyyarChatInputType = NonNullable<_BodyyarChatCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BodyyarChatCfg['execute']>[0]['input'];
export type BodyyarChatOutputType = Awaited<ReturnType<_BodyyarChatCfg['execute']>>;
export const bodyyarChat = createCaller<BodyyarChatInputType, BodyyarChatOutputType>('bodyyarChat');

type _CancelCoachingRequestCfg = typeof _CancelCoachingRequestEp;
export type CancelCoachingRequestInputType = NonNullable<_CancelCoachingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CancelCoachingRequestCfg['execute']>[0]['input'];
export type CancelCoachingRequestOutputType = Awaited<ReturnType<_CancelCoachingRequestCfg['execute']>>;
export const cancelCoachingRequest = createCaller<CancelCoachingRequestInputType, CancelCoachingRequestOutputType>('cancelCoachingRequest');

type _ChallengeProgressCfg = typeof _ChallengeProgressEp;
export type ChallengeProgressInputType = NonNullable<_ChallengeProgressCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ChallengeProgressCfg['execute']>[0]['input'];
export type ChallengeProgressOutputType = Awaited<ReturnType<_ChallengeProgressCfg['execute']>>;
export const challengeProgress = createCaller<ChallengeProgressInputType, ChallengeProgressOutputType>('challengeProgress');

type _CreateCoachingRequestCfg = typeof _CreateCoachingRequestEp;
export type CreateCoachingRequestInputType = NonNullable<_CreateCoachingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateCoachingRequestCfg['execute']>[0]['input'];
export type CreateCoachingRequestOutputType = Awaited<ReturnType<_CreateCoachingRequestCfg['execute']>>;
export const createCoachingRequest = createCaller<CreateCoachingRequestInputType, CreateCoachingRequestOutputType>('createCoachingRequest');

type _GenerateWorkoutPlanCfg = typeof _GenerateWorkoutPlanEp;
export type GenerateWorkoutPlanInputType = NonNullable<_GenerateWorkoutPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateWorkoutPlanCfg['execute']>[0]['input'];
export type GenerateWorkoutPlanOutputType = Awaited<ReturnType<_GenerateWorkoutPlanCfg['execute']>>;
export const generateWorkoutPlan = createCaller<GenerateWorkoutPlanInputType, GenerateWorkoutPlanOutputType>('generateWorkoutPlan');

type _GetCatalogCfg = typeof _GetCatalogEp;
export type GetCatalogInputType = NonNullable<_GetCatalogCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCatalogCfg['execute']>[0]['input'];
export type GetCatalogOutputType = Awaited<ReturnType<_GetCatalogCfg['execute']>>;
export const getCatalog = createCaller<GetCatalogInputType, GetCatalogOutputType>('getCatalog');

type _GetCoachPanelCfg = typeof _GetCoachPanelEp;
export type GetCoachPanelInputType = NonNullable<_GetCoachPanelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCoachPanelCfg['execute']>[0]['input'];
export type GetCoachPanelOutputType = Awaited<ReturnType<_GetCoachPanelCfg['execute']>>;
export const getCoachPanel = createCaller<GetCoachPanelInputType, GetCoachPanelOutputType>('getCoachPanel');

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

type _GetMessagesCfg = typeof _GetMessagesEp;
export type GetMessagesInputType = NonNullable<_GetMessagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMessagesCfg['execute']>[0]['input'];
export type GetMessagesOutputType = Awaited<ReturnType<_GetMessagesCfg['execute']>>;
export const getMessages = createCaller<GetMessagesInputType, GetMessagesOutputType>('getMessages');

type _JamendoTracksCfg = typeof _JamendoTracksEp;
export type JamendoTracksInputType = NonNullable<_JamendoTracksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_JamendoTracksCfg['execute']>[0]['input'];
export type JamendoTracksOutputType = Awaited<ReturnType<_JamendoTracksCfg['execute']>>;
export const jamendoTracks = createCaller<JamendoTracksInputType, JamendoTracksOutputType>('jamendoTracks');

type _KapooshProductsCfg = typeof _KapooshProductsEp;
export type KapooshProductsInputType = NonNullable<_KapooshProductsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_KapooshProductsCfg['execute']>[0]['input'];
export type KapooshProductsOutputType = Awaited<ReturnType<_KapooshProductsCfg['execute']>>;
export const kapooshProducts = createCaller<KapooshProductsInputType, KapooshProductsOutputType>('kapooshProducts');

type _ListConversationsCfg = typeof _ListConversationsEp;
export type ListConversationsInputType = NonNullable<_ListConversationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListConversationsCfg['execute']>[0]['input'];
export type ListConversationsOutputType = Awaited<ReturnType<_ListConversationsCfg['execute']>>;
export const listConversations = createCaller<ListConversationsInputType, ListConversationsOutputType>('listConversations');

type _LogActivityCfg = typeof _LogActivityEp;
export type LogActivityInputType = NonNullable<_LogActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LogActivityCfg['execute']>[0]['input'];
export type LogActivityOutputType = Awaited<ReturnType<_LogActivityCfg['execute']>>;
export const logActivity = createCaller<LogActivityInputType, LogActivityOutputType>('logActivity');

type _RedeemRewardCfg = typeof _RedeemRewardEp;
export type RedeemRewardInputType = NonNullable<_RedeemRewardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RedeemRewardCfg['execute']>[0]['input'];
export type RedeemRewardOutputType = Awaited<ReturnType<_RedeemRewardCfg['execute']>>;
export const redeemReward = createCaller<RedeemRewardInputType, RedeemRewardOutputType>('redeemReward');

type _SaveAvailabilityCfg = typeof _SaveAvailabilityEp;
export type SaveAvailabilityInputType = NonNullable<_SaveAvailabilityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAvailabilityCfg['execute']>[0]['input'];
export type SaveAvailabilityOutputType = Awaited<ReturnType<_SaveAvailabilityCfg['execute']>>;
export const saveAvailability = createCaller<SaveAvailabilityInputType, SaveAvailabilityOutputType>('saveAvailability');

type _SaveCoachPlanCfg = typeof _SaveCoachPlanEp;
export type SaveCoachPlanInputType = NonNullable<_SaveCoachPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCoachPlanCfg['execute']>[0]['input'];
export type SaveCoachPlanOutputType = Awaited<ReturnType<_SaveCoachPlanCfg['execute']>>;
export const saveCoachPlan = createCaller<SaveCoachPlanInputType, SaveCoachPlanOutputType>('saveCoachPlan');

type _SaveListeningCfg = typeof _SaveListeningEp;
export type SaveListeningInputType = NonNullable<_SaveListeningCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveListeningCfg['execute']>[0]['input'];
export type SaveListeningOutputType = Awaited<ReturnType<_SaveListeningCfg['execute']>>;
export const saveListening = createCaller<SaveListeningInputType, SaveListeningOutputType>('saveListening');

type _SaveProfileCfg = typeof _SaveProfileEp;
export type SaveProfileInputType = NonNullable<_SaveProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProfileCfg['execute']>[0]['input'];
export type SaveProfileOutputType = Awaited<ReturnType<_SaveProfileCfg['execute']>>;
export const saveProfile = createCaller<SaveProfileInputType, SaveProfileOutputType>('saveProfile');

type _SendMessageCfg = typeof _SendMessageEp;
export type SendMessageInputType = NonNullable<_SendMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendMessageCfg['execute']>[0]['input'];
export type SendMessageOutputType = Awaited<ReturnType<_SendMessageCfg['execute']>>;
export const sendMessage = createCaller<SendMessageInputType, SendMessageOutputType>('sendMessage');

type _StartConversationCfg = typeof _StartConversationEp;
export type StartConversationInputType = NonNullable<_StartConversationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_StartConversationCfg['execute']>[0]['input'];
export type StartConversationOutputType = Awaited<ReturnType<_StartConversationCfg['execute']>>;
export const startConversation = createCaller<StartConversationInputType, StartConversationOutputType>('startConversation');

type _TrackCampaignViewCfg = typeof _TrackCampaignViewEp;
export type TrackCampaignViewInputType = NonNullable<_TrackCampaignViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_TrackCampaignViewCfg['execute']>[0]['input'];
export type TrackCampaignViewOutputType = Awaited<ReturnType<_TrackCampaignViewCfg['execute']>>;
export const trackCampaignView = createCaller<TrackCampaignViewInputType, TrackCampaignViewOutputType>('trackCampaignView');

type _UpdateCoachProfileCfg = typeof _UpdateCoachProfileEp;
export type UpdateCoachProfileInputType = NonNullable<_UpdateCoachProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCoachProfileCfg['execute']>[0]['input'];
export type UpdateCoachProfileOutputType = Awaited<ReturnType<_UpdateCoachProfileCfg['execute']>>;
export const updateCoachProfile = createCaller<UpdateCoachProfileInputType, UpdateCoachProfileOutputType>('updateCoachProfile');

type _UpdateRequestStatusCfg = typeof _UpdateRequestStatusEp;
export type UpdateRequestStatusInputType = NonNullable<_UpdateRequestStatusCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateRequestStatusCfg['execute']>[0]['input'];
export type UpdateRequestStatusOutputType = Awaited<ReturnType<_UpdateRequestStatusCfg['execute']>>;
export const updateRequestStatus = createCaller<UpdateRequestStatusInputType, UpdateRequestStatusOutputType>('updateRequestStatus');


export const api = {
  adminList,
  adminListCoaches,
  adminLogin,
  adminReviewCoach,
  adminSave,
  adminStats,
  applyCoach,
  bodyyarChat,
  cancelCoachingRequest,
  challengeProgress,
  createCoachingRequest,
  generateWorkoutPlan,
  getCatalog,
  getCoachPanel,
  getMe,
  getMessages,
  jamendoTracks,
  kapooshProducts,
  listConversations,
  logActivity,
  redeemReward,
  saveAvailability,
  saveCoachPlan,
  saveListening,
  saveProfile,
  sendMessage,
  startConversation,
  trackCampaignView,
  updateCoachProfile,
  updateRequestStatus,
};
