// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _BodyyarChatEp } from '../src/api/bodyyarChat';
import type { default as _CancelCoachingRequestEp } from '../src/api/cancelCoachingRequest';
import type { default as _ChallengeProgressEp } from '../src/api/challengeProgress';
import type { default as _CreateCoachingRequestEp } from '../src/api/createCoachingRequest';
import type { default as _GenerateWorkoutPlanEp } from '../src/api/generateWorkoutPlan';
import type { default as _GetCatalogEp } from '../src/api/getCatalog';
import type { default as _GetMeEp } from '../src/api/getMe';
import type { default as _LogActivityEp } from '../src/api/logActivity';
import type { default as _RedeemRewardEp } from '../src/api/redeemReward';
import type { default as _SaveListeningEp } from '../src/api/saveListening';
import type { default as _SaveProfileEp } from '../src/api/saveProfile';

type _BodyyarChatCfg = typeof _BodyyarChatEp;
export type BodyyarChatInputType = NonNullable<_BodyyarChatCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BodyyarChatCfg['execute']>[0]['input'];
export type BodyyarChatOutputType = Awaited<ReturnType<_BodyyarChatCfg['execute']>>;
export const bodyyarChat = createCaller<BodyyarChatInputType, BodyyarChatOutputType>('bodyyarChat');

type _CancelCoachingRequestCfg = typeof _CancelCoachingRequestEp;
export type CancelCoachingRequestInputType = NonNullable<_CancelCoachingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CancelCoachingRequestCfg['execute']>[0]['input'];
export type CancelCoachingRequestOutputType = Awaited<ReturnType<_CancelCoachingRequestCfg['execute']>>;
export const cancelCoachingRequest = createCaller<CancelCoachingRequestInputType, CancelCoachingRequestOutputType>('cancelCoachingRequest');

type _ChallengeProgressCfg = typeof _ChallengeProgressEp;
export type ChallengeProgressInputType = NonNullable<_ChallengeProgressCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ChallengeProgressCfg['execute']>[0]['input'];
export type ChallengeProgressOutputType = Awaited<ReturnType<_ChallengeProgressCfg['execute']>>;
export const challengeProgress = createCaller<ChallengeProgressInputType, ChallengeProgressOutputType>('challengeProgress');

type _CreateCoachingRequestCfg = typeof _CreateCoachingRequestEp;
export type CreateCoachingRequestInputType = NonNullable<_CreateCoachingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateCoachingRequestCfg['execute']>[0]['input'];
export type CreateCoachingRequestOutputType = Awaited<ReturnType<_CreateCoachingRequestCfg['execute']>>;
export const createCoachingRequest = createCaller<CreateCoachingRequestInputType, CreateCoachingRequestOutputType>('createCoachingRequest');

type _GenerateWorkoutPlanCfg = typeof _GenerateWorkoutPlanEp;
export type GenerateWorkoutPlanInputType = NonNullable<_GenerateWorkoutPlanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateWorkoutPlanCfg['execute']>[0]['input'];
export type GenerateWorkoutPlanOutputType = Awaited<ReturnType<_GenerateWorkoutPlanCfg['execute']>>;
export const generateWorkoutPlan = createCaller<GenerateWorkoutPlanInputType, GenerateWorkoutPlanOutputType>('generateWorkoutPlan');

type _GetCatalogCfg = typeof _GetCatalogEp;
export type GetCatalogInputType = NonNullable<_GetCatalogCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCatalogCfg['execute']>[0]['input'];
export type GetCatalogOutputType = Awaited<ReturnType<_GetCatalogCfg['execute']>>;
export const getCatalog = createCaller<GetCatalogInputType, GetCatalogOutputType>('getCatalog');

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

type _LogActivityCfg = typeof _LogActivityEp;
export type LogActivityInputType = NonNullable<_LogActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LogActivityCfg['execute']>[0]['input'];
export type LogActivityOutputType = Awaited<ReturnType<_LogActivityCfg['execute']>>;
export const logActivity = createCaller<LogActivityInputType, LogActivityOutputType>('logActivity');

type _RedeemRewardCfg = typeof _RedeemRewardEp;
export type RedeemRewardInputType = NonNullable<_RedeemRewardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RedeemRewardCfg['execute']>[0]['input'];
export type RedeemRewardOutputType = Awaited<ReturnType<_RedeemRewardCfg['execute']>>;
export const redeemReward = createCaller<RedeemRewardInputType, RedeemRewardOutputType>('redeemReward');

type _SaveListeningCfg = typeof _SaveListeningEp;
export type SaveListeningInputType = NonNullable<_SaveListeningCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveListeningCfg['execute']>[0]['input'];
export type SaveListeningOutputType = Awaited<ReturnType<_SaveListeningCfg['execute']>>;
export const saveListening = createCaller<SaveListeningInputType, SaveListeningOutputType>('saveListening');

type _SaveProfileCfg = typeof _SaveProfileEp;
export type SaveProfileInputType = NonNullable<_SaveProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProfileCfg['execute']>[0]['input'];
export type SaveProfileOutputType = Awaited<ReturnType<_SaveProfileCfg['execute']>>;
export const saveProfile = createCaller<SaveProfileInputType, SaveProfileOutputType>('saveProfile');


export const api = {
  bodyyarChat,
  cancelCoachingRequest,
  challengeProgress,
  createCoachingRequest,
  generateWorkoutPlan,
  getCatalog,
  getMe,
  logActivity,
  redeemReward,
  saveListening,
  saveProfile,
};
