// Generated by Zite. Do not edit.
// Prefer `integrations.get('<name>')` from 'zitejs/integrations': these names
// change when another account of a type is connected; a name does not.
declare namespace NodeJS {
  interface ProcessEnv {
    /** Public URL of the current app. */
    ZITE_APP_URL: string;
    /** github access token (github) */
    ZITE_GITHUB_ACCESS_TOKEN: string;
    /** Jamendo API Client ID (from devportal.jamendo.com) used server-side to list/search playable tracks for Morshed */
    ZITE_JAMENDO_CLIENT_ID: string;
    [key: string]: string | undefined;
  }
}
