// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "CoachPlansCoaches" — columns: "coachPlansId", "coachesId" (joins "Coach Plans" and "Coaches")
//   "CoachesCoachingRequests" — columns: "coachesId", "coachingRequestsId" (joins "Coaches" and "Coaching Requests")
//   "CoachPlansCoachingRequests" — columns: "coachPlansId", "coachingRequestsId" (joins "Coach Plans" and "Coaching Requests")
//   "AudioContentsListeningProgress" — columns: "audioContentsId", "listeningProgressId" (joins "Audio Contents" and "Listening Progress")
//   "CampaignsChallenges" — columns: "campaignsId", "challengesId" (joins "Campaigns" and "Challenges")
//   "ChallengeParticipationsChallenges" — columns: "challengeParticipationsId", "challengesId" (joins "Challenge Participations" and "Challenges")
//   "RewardRedemptionsRewards" — columns: "rewardRedemptionsId", "rewardsId" (joins "Reward Redemptions" and "Rewards")
//   "CoachingRequestsPayments" — columns: "coachingRequestsId", "paymentsId" (joins "Coaching Requests" and "Payments")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Profiles" table, as it is read back. */
export type ProfilesRecordType = {
  id: string;
  /** Primary field. "Display Name" */
  displayName?: string;
  user?: string | string[];
  phone?: string;
  /** "Height Cm". 1 decimal places, format: local (e.g. 1,000,000.50) */
  heightCm?: number;
  /** "Weight Kg". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weightKg?: number;
  /** "Age". 1 decimal places, format: local (e.g. 1,000,000.50) */
  age?: number;
  gender?: "مرد" | "زن" | string;
  goal?: "کاهش وزن" | "افزایش حجم" | "آمادگی جسمانی" | "سلامت و انرژی" | string;
  level?: "مبتدی" | "متوسط" | "پیشرفته" | string;
  equipment?: "بدون تجهیزات" | "تجهیزات خانگی" | "باشگاه کامل" | string;
  healthNotes?: string;
  /** "Points". 1 decimal places, format: local (e.g. 1,000,000.50) */
  points?: number;
  onboarded?: boolean;
};

/** What you may write when creating or updating a record in the "Profiles" table. */
export type ProfilesRecordInput = {
  displayName: string | null;
  user: string | string[] | null;
  phone: string | null;
  heightCm: string | number | null;
  weightKg: string | number | null;
  age: string | number | null;
  gender: "مرد" | "زن" | string | null;
  goal: "کاهش وزن" | "افزایش حجم" | "آمادگی جسمانی" | "سلامت و انرژی" | string | null;
  level: "مبتدی" | "متوسط" | "پیشرفته" | string | null;
  equipment: "بدون تجهیزات" | "تجهیزات خانگی" | "باشگاه کامل" | string | null;
  healthNotes: string | null;
  points: string | number | null;
  onboarded: string | boolean | null;
};

/** A record in the "Coaches" table, as it is read back. */
export type CoachesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  title?: string;
  specialties?: ("فیتنس" | "بدنسازی" | "کاردیو" | "یوگا" | "تغذیه" | "اصلاح فرم" | string)[];
  bio?: string;
  avatarUrl?: string;
  /** "Years Experience". 1 decimal places, format: local (e.g. 1,000,000.50) */
  yearsExperience?: number;
  /** "Rating". 1 decimal places, format: local (e.g. 1,000,000.50) */
  rating?: number;
  /** "Review Count". 1 decimal places, format: local (e.g. 1,000,000.50) */
  reviewCount?: number;
  certifications?: string;
  status?: "در انتظار تایید" | "تایید شده" | "معلق" | string;
  user?: string | string[];
  /** Links to coachPlans ("Coach Plans"). "Coach Plans" */
  coachPlans?: string | string[];
  /** Links to coachingRequests ("Coaching Requests"). "Coaching Requests" */
  coachingRequests?: string | string[];
};

/** What you may write when creating or updating a record in the "Coaches" table. */
export type CoachesRecordInput = {
  name: string | null;
  title: string | null;
  specialties: "فیتنس" | "بدنسازی" | "کاردیو" | "یوگا" | "تغذیه" | "اصلاح فرم" | string | ("فیتنس" | "بدنسازی" | "کاردیو" | "یوگا" | "تغذیه" | "اصلاح فرم" | string)[] | null;
  bio: string | null;
  avatarUrl: string | null;
  yearsExperience: string | number | null;
  rating: string | number | null;
  reviewCount: string | number | null;
  certifications: string | null;
  status: "در انتظار تایید" | "تایید شده" | "معلق" | string | null;
  user: string | string[] | null;
  coachPlans: string | string[] | null;
  coachingRequests: string | string[] | null;
};

/** A record in the "Coach Plans" table, as it is read back. */
export type CoachPlansRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  /** Links to coaches ("Coaches"). "Coach" */
  coach?: string | string[];
  /** "Sessions". 1 decimal places, format: local (e.g. 1,000,000.50) */
  sessions?: number;
  /** "Duration Weeks". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationWeeks?: number;
  /** "Price". Value is a raw number; display as currency with symbol "تومان", 0 decimal places, format: local (e.g. 1,000,000.50) */
  price?: number;
  description?: string;
  /** Links to coachingRequests ("Coaching Requests"). "Coaching Requests" */
  coachingRequests?: string | string[];
};

/** What you may write when creating or updating a record in the "Coach Plans" table. */
export type CoachPlansRecordInput = {
  name: string | null;
  coach: string | string[] | null;
  sessions: string | number | null;
  durationWeeks: string | number | null;
  price: string | number | null;
  description: string | null;
  coachingRequests: string | string[] | null;
};

/** A record in the "Coaching Requests" table, as it is read back. */
export type CoachingRequestsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  client?: string | string[];
  /** Links to coaches ("Coaches"). "Coach" */
  coach?: string | string[];
  /** Links to coachPlans ("Coach Plans"). "Plan" */
  plan?: string | string[];
  status?: "در انتظار" | "پذیرفته شده" | "رد شده" | "لغو شده" | string;
  message?: string;
  /** "Session At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sessionAt?: string;
  /** Links to payments ("Payments"). "Payments" */
  payments?: string | string[];
};

/** What you may write when creating or updating a record in the "Coaching Requests" table. */
export type CoachingRequestsRecordInput = {
  title: string | null;
  client: string | string[] | null;
  coach: string | string[] | null;
  plan: string | string[] | null;
  status: "در انتظار" | "پذیرفته شده" | "رد شده" | "لغو شده" | string | null;
  message: string | null;
  sessionAt: string | Date | null;
  payments: string | string[] | null;
};

/** A record in the "Workout Plans" table, as it is read back. */
export type WorkoutPlansRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  owner?: string | string[];
  content?: string;
  source?: "بدن‌یار" | "مربی" | "دستی" | string;
  status?: "فعال" | "بایگانی" | string;
};

/** What you may write when creating or updating a record in the "Workout Plans" table. */
export type WorkoutPlansRecordInput = {
  title: string | null;
  owner: string | string[] | null;
  content: string | null;
  source: "بدن‌یار" | "مربی" | "دستی" | string | null;
  status: "فعال" | "بایگانی" | string | null;
};

/** A record in the "Activity Logs" table, as it is read back. */
export type ActivityLogsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  owner?: string | string[];
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  /** "Duration Minutes". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  /** "Calories". 1 decimal places, format: local (e.g. 1,000,000.50) */
  calories?: number;
  /** "Weight Kg". 1 decimal places, format: local (e.g. 1,000,000.50) */
  weightKg?: number;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Activity Logs" table. */
export type ActivityLogsRecordInput = {
  title: string | null;
  owner: string | string[] | null;
  date: string | Date | null;
  durationMinutes: string | number | null;
  calories: string | number | null;
  weightKg: string | number | null;
  notes: string | null;
};

/** A record in the "Bodyyar Messages" table, as it is read back. */
export type BodyyarMessagesRecordType = {
  id: string;
  /** Primary field. "Content" */
  content?: string;
  owner?: string | string[];
  role?: "user" | "assistant" | string;
  /** Read-only. "Created". Auto-set when record was created (ISO 8601) */
  created?: string;
};

/** What you may write when creating or updating a record in the "Bodyyar Messages" table. */
export type BodyyarMessagesRecordInput = {
  content: string | null;
  owner: string | string[] | null;
  role: "user" | "assistant" | string | null;
};

/** A record in the "Audio Contents" table, as it is read back. */
export type AudioContentsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  category?: "پادکست" | "آموزشی" | "انگیزشی" | "موسیقی تمرین" | string;
  description?: string;
  audioUrl?: string;
  coverUrl?: string;
  /** "Duration Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  durationSeconds?: number;
  author?: string;
  published?: boolean;
  /** Links to listeningProgress ("Listening Progress"). "Listening Progress" */
  listeningProgress?: string | string[];
};

/** What you may write when creating or updating a record in the "Audio Contents" table. */
export type AudioContentsRecordInput = {
  title: string | null;
  category: "پادکست" | "آموزشی" | "انگیزشی" | "موسیقی تمرین" | string | null;
  description: string | null;
  audioUrl: string | null;
  coverUrl: string | null;
  durationSeconds: string | number | null;
  author: string | null;
  published: string | boolean | null;
  listeningProgress: string | string[] | null;
};

/** A record in the "Listening Progress" table, as it is read back. */
export type ListeningProgressRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  owner?: string | string[];
  /** Links to audioContents ("Audio Contents"). "Content" */
  content?: string | string[];
  /** "Position Seconds". 1 decimal places, format: local (e.g. 1,000,000.50) */
  positionSeconds?: number;
  saved?: boolean;
};

/** What you may write when creating or updating a record in the "Listening Progress" table. */
export type ListeningProgressRecordInput = {
  label: string | null;
  owner: string | string[] | null;
  content: string | string[] | null;
  positionSeconds: string | number | null;
  saved: string | boolean | null;
};

/** A record in the "Campaigns" table, as it is read back. */
export type CampaignsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  brand?: string;
  description?: string;
  coverUrl?: string;
  /** "Starts On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startsOn?: string;
  /** "Ends On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  endsOn?: string;
  status?: "پیش‌نویس" | "فعال" | "پایان یافته" | string;
  /** "Views". 1 decimal places, format: local (e.g. 1,000,000.50) */
  views?: number;
  /** Links to challenges ("Challenges"). "Challenges" */
  challenges?: string | string[];
};

/** What you may write when creating or updating a record in the "Campaigns" table. */
export type CampaignsRecordInput = {
  title: string | null;
  brand: string | null;
  description: string | null;
  coverUrl: string | null;
  startsOn: string | Date | null;
  endsOn: string | Date | null;
  status: "پیش‌نویس" | "فعال" | "پایان یافته" | string | null;
  views: string | number | null;
  challenges: string | string[] | null;
};

/** A record in the "Challenges" table, as it is read back. */
export type ChallengesRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  description?: string;
  /** "Target". 1 decimal places, format: local (e.g. 1,000,000.50) */
  target?: number;
  unit?: string;
  /** "Points". 1 decimal places, format: local (e.g. 1,000,000.50) */
  points?: number;
  /** "Ends On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  endsOn?: string;
  /** Links to campaigns ("Campaigns"). "Campaign" */
  campaign?: string | string[];
  active?: boolean;
  /** Links to challengeParticipations ("Challenge Participations"). "Challenge Participations" */
  challengeParticipations?: string | string[];
};

/** What you may write when creating or updating a record in the "Challenges" table. */
export type ChallengesRecordInput = {
  title: string | null;
  description: string | null;
  target: string | number | null;
  unit: string | null;
  points: string | number | null;
  endsOn: string | Date | null;
  campaign: string | string[] | null;
  active: string | boolean | null;
  challengeParticipations: string | string[] | null;
};

/** A record in the "Challenge Participations" table, as it is read back. */
export type ChallengeParticipationsRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  owner?: string | string[];
  /** Links to challenges ("Challenges"). "Challenge" */
  challenge?: string | string[];
  /** "Progress". 1 decimal places, format: local (e.g. 1,000,000.50) */
  progress?: number;
  completed?: boolean;
};

/** What you may write when creating or updating a record in the "Challenge Participations" table. */
export type ChallengeParticipationsRecordInput = {
  label: string | null;
  owner: string | string[] | null;
  challenge: string | string[] | null;
  progress: string | number | null;
  completed: string | boolean | null;
};

/** A record in the "Rewards" table, as it is read back. */
export type RewardsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  description?: string;
  /** "Cost Points". 1 decimal places, format: local (e.g. 1,000,000.50) */
  costPoints?: number;
  kind?: "کد تخفیف" | "لباس" | "اشتراک" | string;
  /** "Stock". 1 decimal places, format: local (e.g. 1,000,000.50) */
  stock?: number;
  /** Links to rewardRedemptions ("Reward Redemptions"). "Reward Redemptions" */
  rewardRedemptions?: string | string[];
};

/** What you may write when creating or updating a record in the "Rewards" table. */
export type RewardsRecordInput = {
  title: string | null;
  description: string | null;
  costPoints: string | number | null;
  kind: "کد تخفیف" | "لباس" | "اشتراک" | string | null;
  stock: string | number | null;
  rewardRedemptions: string | string[] | null;
};

/** A record in the "Reward Redemptions" table, as it is read back. */
export type RewardRedemptionsRecordType = {
  id: string;
  /** Primary field. "Code" */
  code?: string;
  owner?: string | string[];
  /** Links to rewards ("Rewards"). "Reward" */
  reward?: string | string[];
};

/** What you may write when creating or updating a record in the "Reward Redemptions" table. */
export type RewardRedemptionsRecordInput = {
  code: string | null;
  owner: string | string[] | null;
  reward: string | string[] | null;
};

/** A record in the "Payments" table, as it is read back. */
export type PaymentsRecordType = {
  id: string;
  /** Primary field. "Reference" */
  reference?: string;
  payer?: string | string[];
  /** "Amount". Value is a raw number; display as currency with symbol "تومان", 0 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  status?: "در انتظار درگاه" | "موفق" | "ناموفق" | string;
  provider?: string;
  /** Links to coachingRequests ("Coaching Requests"). "Request" */
  request?: string | string[];
};

/** What you may write when creating or updating a record in the "Payments" table. */
export type PaymentsRecordInput = {
  reference: string | null;
  payer: string | string[] | null;
  amount: string | number | null;
  status: "در انتظار درگاه" | "موفق" | "ناموفق" | string | null;
  provider: string | null;
  request: string | string[] | null;
};

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  profiles: createTableClient<ProfilesRecordType, ProfilesRecordInput>('Profiles'), // "Profiles"
  coaches: createTableClient<CoachesRecordType, CoachesRecordInput>('Coaches'), // "Coaches"
  coachPlans: createTableClient<CoachPlansRecordType, CoachPlansRecordInput>('CoachPlans'), // "Coach Plans"
  coachingRequests: createTableClient<CoachingRequestsRecordType, CoachingRequestsRecordInput>('CoachingRequests'), // "Coaching Requests"
  workoutPlans: createTableClient<WorkoutPlansRecordType, WorkoutPlansRecordInput>('WorkoutPlans'), // "Workout Plans"
  activityLogs: createTableClient<ActivityLogsRecordType, ActivityLogsRecordInput>('ActivityLogs'), // "Activity Logs"
  bodyyarMessages: createTableClient<BodyyarMessagesRecordType, BodyyarMessagesRecordInput>('BodyyarMessages'), // "Bodyyar Messages"
  audioContents: createTableClient<AudioContentsRecordType, AudioContentsRecordInput>('AudioContents'), // "Audio Contents"
  listeningProgress: createTableClient<ListeningProgressRecordType, ListeningProgressRecordInput>('ListeningProgress'), // "Listening Progress"
  campaigns: createTableClient<CampaignsRecordType, CampaignsRecordInput>('Campaigns'), // "Campaigns"
  challenges: createTableClient<ChallengesRecordType, ChallengesRecordInput>('Challenges'), // "Challenges"
  challengeParticipations: createTableClient<ChallengeParticipationsRecordType, ChallengeParticipationsRecordInput>('ChallengeParticipations'), // "Challenge Participations"
  rewards: createTableClient<RewardsRecordType, RewardsRecordInput>('Rewards'), // "Rewards"
  rewardRedemptions: createTableClient<RewardRedemptionsRecordType, RewardRedemptionsRecordInput>('RewardRedemptions'), // "Reward Redemptions"
  payments: createTableClient<PaymentsRecordType, PaymentsRecordInput>('Payments'), // "Payments"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
