// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AdminListEp } from '../src/api/adminList';
import type { default as _AdminSaveEp } from '../src/api/adminSave';
import type { default as _AdminStatsEp } from '../src/api/adminStats';
import type { default as _ListCoachesEp } from '../src/api/listCoaches';
import type { default as _ReviewCoachEp } from '../src/api/reviewCoach';

type _AdminListCfg = typeof _AdminListEp;
export type AdminListInputType = NonNullable<_AdminListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminListCfg['execute']>[0]['input'];
export type AdminListOutputType = Awaited<ReturnType<_AdminListCfg['execute']>>;
export const adminList = createCaller<AdminListInputType, AdminListOutputType>('adminList');

type _AdminSaveCfg = typeof _AdminSaveEp;
export type AdminSaveInputType = NonNullable<_AdminSaveCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminSaveCfg['execute']>[0]['input'];
export type AdminSaveOutputType = Awaited<ReturnType<_AdminSaveCfg['execute']>>;
export const adminSave = createCaller<AdminSaveInputType, AdminSaveOutputType>('adminSave');

type _AdminStatsCfg = typeof _AdminStatsEp;
export type AdminStatsInputType = NonNullable<_AdminStatsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AdminStatsCfg['execute']>[0]['input'];
export type AdminStatsOutputType = Awaited<ReturnType<_AdminStatsCfg['execute']>>;
export const adminStats = createCaller<AdminStatsInputType, AdminStatsOutputType>('adminStats');

type _ListCoachesCfg = typeof _ListCoachesEp;
export type ListCoachesInputType = NonNullable<_ListCoachesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCoachesCfg['execute']>[0]['input'];
export type ListCoachesOutputType = Awaited<ReturnType<_ListCoachesCfg['execute']>>;
export const listCoaches = createCaller<ListCoachesInputType, ListCoachesOutputType>('listCoaches');

type _ReviewCoachCfg = typeof _ReviewCoachEp;
export type ReviewCoachInputType = NonNullable<_ReviewCoachCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReviewCoachCfg['execute']>[0]['input'];
export type ReviewCoachOutputType = Awaited<ReturnType<_ReviewCoachCfg['execute']>>;
export const reviewCoach = createCaller<ReviewCoachInputType, ReviewCoachOutputType>('reviewCoach');


export const api = {
  adminList,
  adminSave,
  adminStats,
  listCoaches,
  reviewCoach,
};
